export {
  ApiClient,
  AuthApi,
  UsersApi,
  createApiClient,
  defaultConfig,
  type ApiClientConfig,
  type RequestOptions,
  type RequestOtpParams,
  type VerifyOtpParams,
  type SessionInfo,
  type SessionDetails,
  type RevokeSessionsResponse,
  type AuthSession,
  type AvatarInfo,
  type UserProfile,
  type RequestEmailVerificationParams,
  type VerifyEmailParams,
  type RequestPhoneVerificationParams,
  type VerifyPhoneParams,
} from './client';
