export {
  ApiClient,
  AuthApi,
  UsersApi,
  MfaApi,
  IdentityApi,
  createApiClient,
  defaultConfig,
  type ApiClientConfig,
  type RequestOptions,
  type RequestOtpParams,
  type VerifyOtpParams,
  type VerifyOtpResponse,
  type SessionInfo,
  type SessionDetails,
  type RevokeSessionsResponse,
  type AuthSession,
  type AvatarInfo,
  type UserProfile,
  type RequestEmailVerificationParams,
  type VerifyEmailParams,
  type RequestPhoneVerificationParams,
  type VerifyPhoneParams,
  // MFA types
  type MfaStatus,
  type TotpCredential,
  type WebAuthnCredential,
  type MfaCredentials,
  type TotpSetupResponse,
  type TotpVerifyResponse,
  type WebAuthnRegisterStartResponse,
  type WebAuthnRegisterFinishResponse,
  type BackupCodesResponse,
  type PublicKeyCredentialCreationOptionsJSON,
  type PublicKeyCredentialRequestOptionsJSON,
  // Identity types
  type PublicIdentity,
  type CreateIdentityParams,
  type LoginIdentityParams,
  type IdentityLoginResponse,
  type IdentityLoginErrorResponse,
} from './client';
