/**
 * Maps semantic app icon names to FontAwesome icon names.
 *
 * Consumers use the keys (e.g. `"home"`, `"message"`); the Icon component
 * resolves them to the corresponding FA identifier at render time.
 */

export const APP_ICON_NAMES = {
  home: 'house',
  message: 'message',
  reply: 'reply',
  users: 'users',
  settings: 'gear',
  info: 'circle-info',
  download: 'download',
  copy: 'copy',
  /** Copy entire text field (e.g. composer). */
  copyAll: 'files',
  /** Text field “select all” (e.g. composer context menu). */
  selectAll: 'border-all',
  link: 'link',
  externalLink: 'arrow-up-right-from-square',
  /** Upload / attach (image, video, files). */
  upload: 'arrow-up-from-bracket',
  film: 'film',
  logout: 'right-from-bracket',
  shield: 'shield-check',
  key: 'key',
  bell: 'bell',
  search: 'magnifying-glass',
  user: 'user',
  palette: 'palette',
  lock: 'lock',
  mask: 'mask',
  plus: 'plus',
  check: 'check',
  clock: 'clock',
  x: 'xmark',
  spaces: 'grid-2',
  ellipsis: 'ellipsis',
  ellipsisVertical: 'ellipsis-vertical',
  smile: 'face-smile',
  smilePlus: 'face-smile-plus',
  send: 'paper-plane',
  trash: 'trash',
  fileExport: 'file-export',
  fileImport: 'file-import',
  chevronDown: 'chevron-down',
  chevronRight: 'chevron-right',
  chevronUp: 'chevron-up',
  camera: 'camera',
  image: 'image',
  globe: 'globe',
  desktop: 'desktop',
  bars: 'bars',
  eye: 'eye',
  eyeSlash: 'eye-slash',
  thumbsUp: 'thumbs-up',
  warning: 'triangle-exclamation',
  success: 'circle-check',
  error: 'circle-xmark',
  badgeCheck: 'badge-check',
  fileArrowDown: 'file-arrow-down',
  fileArrowUp: 'file-arrow-up',
  arrowLeft: 'arrow-left',
  arrowRight: 'arrow-right',
  circle: 'circle',
  pen: 'pen',
  noteSticky: 'note-sticky',
  trophy: 'trophy',
  userPlus: 'user-plus',
  group: 'user-group',
  device: 'mobile-screen-button',
  heart: 'heart',
  ban: 'ban',
  gavel: 'gavel',
  fire: 'fire',
  userMinus: 'user-minus',
  archive: 'box-archive',
  star: 'star',
  filter: 'filter',
  sortAlpha: 'arrow-down-a-z',
  pin: 'thumbtack',
  focusFrame: 'arrows-to-eye',
  locationPin: 'location-pin',
  rotateRight: 'arrow-rotate-right',
  handshake: 'handshake',
  personPregnant: 'person-pregnant',
  creditCard: 'credit-card',
  phone: 'phone',
  phoneHangup: 'phone-hangup',
  video: 'video',
  videoSlash: 'video-slash',
  microphone: 'microphone',
  microphoneSlash: 'microphone-slash',
  screenShare: 'screen-users',
  phoneIncoming: 'phone-arrow-down-left',
  expand: 'maximize',
  compress: 'compress',
  signalBars: 'signal-bars',
  signalBarsGood: 'signal-bars-good',
  signalBarsFair: 'signal-bars-fair',
  signalBarsWeak: 'signal-bars-weak',
} as const;

export type AppIconName = keyof typeof APP_ICON_NAMES;
