/**
 * Icon registry -- imports required icons from every pack/weight and
 * registers them with the FontAwesome SVG core library.
 *
 * This file must be imported once at app startup (before any Icon component
 * renders) so that `findIconDefinition` can resolve icons by prefix + name.
 *
 * DuoTone Solid / Thin use the full app icon set for those styles; missing
 * glyphs still fall back to Sharp DuoTone Solid at render time (Icon component).
 */

import { library } from '@fortawesome/fontawesome-svg-core';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

// ---------------------------------------------------------------------------
// Classic Solid
// ---------------------------------------------------------------------------

import {
  faHouse as fasHouse, faMessage as fasMessage, faReply as fasReply, faUsers as fasUsers,
  faGear as fasGear, faCircleInfo as fasCircleInfo, faDownload as fasDownload,
  faRightFromBracket as fasLogout, faShieldCheck as fasShield,
  faKey as fasKey, faBell as fasBell, faMagnifyingGlass as fasSearch,
  faUser as fasUser, faPalette as fasPalette, faLock as fasLock,
  faMask as fasMask, faPlus as fasPlus, faCheck as fasCheck,
  faClock as fasClock, faXmark as fasX, faGrid2 as fasSpaces,
  faEllipsis as fasEllipsis, faEllipsisVertical as fasEllipsisVertical,
  faLocationPin as fasLocationPin, faThumbtack as fasThumbtack, faFaceSmile as fasSmile,
  faFaceSmilePlus as fasSmilePlus, faPaperPlane as fasSend,
  faTrash as fasTrash, faFileExport as fasFileExport,
  faFileImport as fasFileImport, faChevronDown as fasChevronDown,
  faChevronRight as fasChevronRight, faChevronUp as fasChevronUp,
  faCamera as fasCamera, faImage as fasImage, faGlobe as fasGlobe,
  faDesktop as fasDesktop, faBars as fasBars, faEye as fasEye,
  faThumbsUp as fasThumbsUp, faTriangleExclamation as fasWarning,
  faCircleCheck as fasSuccess, faCircleXmark as fasError,
  faBadgeCheck as fasBadge, faFileArrowDown as fasFileDown,
  faFileArrowUp as fasFileUp, faArrowLeft as fasArrowLeft, faArrowRight as fasArrowRight,
  faCircle as fasCircle, faPen as fasPen, faNoteSticky as fasNoteSticky,
  faTrophy as fasTrophy, faUserPlus as fasUserPlus,
  faUserGroup as fasUserGroup, faMobileScreenButton as fasMobile,
  faHeart as fasHeart, faBan as fasBan, faGavel as fasGavel,
  faFire as fasFire, faUserMinus as fasUserMinus,
  faBoxArchive as fasBoxArchive, faStar as fasStar,
  faFilter as fasFilter, faArrowDownAZ as fasArrowDownAZ,
  faCopy as fasCopy, faFiles as fasFiles, faBorderAll as fasBorderAll, faLink as fasLink,
  faArrowUpRightFromSquare as fasExternalLink,
  faArrowUpFromBracket as fasArrowUpFromBracket, faFilm as fasFilm,
  faPhone as fasPhone, faPhoneHangup as fasPhoneHangup, faVideo as fasVideo,
  faVideoSlash as fasVideoSlash, faMicrophone as fasMicrophone,
  faMicrophoneSlash as fasMicrophoneSlash, faScreenUsers as fasScreenUsers,
  faMaximize as fasMaximize, faCompress as fasCompress,
  faArrowsToEye as fasArrowsToEye,
  faPhoneArrowDownLeft as fasPhoneArrowDownLeft,
  faEyeSlash as fasEyeSlash,
  faSignalBars as fasSignalBars, faSignalBarsGood as fasSignalBarsGood,
  faSignalBarsFair as fasSignalBarsFair, faSignalBarsWeak as fasSignalBarsWeak,
  faHandshake as fasHandshake,
  faPersonPregnant as fasPersonPregnant,
  faCreditCard as fasCreditCard,
} from '@adieuu-llc/fa-pro-solid-svg-icons';

// ---------------------------------------------------------------------------
// DuoTone Solid
// ---------------------------------------------------------------------------

import {
  faHouse as fadHouse, faMessage as fadMessage, faReply as fadReply, faUsers as fadUsers,
  faGear as fadGear, faCircleInfo as fadCircleInfo, faDownload as fadDownload,
  faRightFromBracket as fadLogout, faShieldCheck as fadShield,
  faKey as fadKey, faBell as fadBell, faMagnifyingGlass as fadSearch,
  faUser as fadUser, faPalette as fadPalette, faLock as fadLock,
  faMask as fadMask, faPlus as fadPlus, faCheck as fadCheck,
  faClock as fadClock, faXmark as fadX, faGrid2 as fadSpaces,
  faEllipsis as fadEllipsis, faEllipsisVertical as fadEllipsisVertical,
  faLocationPin as fadLocationPin, faThumbtack as fadThumbtack, faFaceSmile as fadSmile,
  faFaceSmilePlus as fadSmilePlus, faPaperPlane as fadSend,
  faTrash as fadTrash, faFileExport as fadFileExport,
  faFileImport as fadFileImport, faChevronDown as fadChevronDown,
  faChevronRight as fadChevronRight, faChevronUp as fadChevronUp,
  faCamera as fadCamera, faImage as fadImage, faGlobe as fadGlobe,
  faDesktop as fadDesktop, faBars as fadBars, faEye as fadEye,
  faThumbsUp as fadThumbsUp, faTriangleExclamation as fadWarning,
  faCircleCheck as fadSuccess, faCircleXmark as fadError,
  faBadgeCheck as fadBadge, faFileArrowDown as fadFileDown,
  faFileArrowUp as fadFileUp, faArrowLeft as fadArrowLeft, faArrowRight as fadArrowRight,
  faCircle as fadCircle, faPen as fadPen,
  faNoteSticky as fadNoteSticky,
  faTrophy as fadTrophy, faUserPlus as fadUserPlus,
  faUserGroup as fadUserGroup, faMobileScreenButton as fadMobile,
  faHeart as fadHeart, faBan as fadBan, faGavel as fadGavel,
  faFire as fadFire, faUserMinus as fadUserMinus,
  faBoxArchive as fadBoxArchive, faStar as fadStar,
  faFilter as fadFilter, faArrowDownAZ as fadArrowDownAZ,
  faCopy as fadCopy, faFiles as fadFiles, faBorderAll as fadBorderAll, faLink as fadLink,
  faArrowUpRightFromSquare as fadExternalLink,
  faArrowUpFromBracket as fadArrowUpFromBracket, faFilm as fadFilm,
  faPhone as fadPhone, faPhoneHangup as fadPhoneHangup, faVideo as fadVideo,
  faVideoSlash as fadVideoSlash, faMicrophone as fadMicrophone,
  faMicrophoneSlash as fadMicrophoneSlash, faScreenUsers as fadScreenUsers,
  faMaximize as fadMaximize, faCompress as fadCompress,
  faArrowsToEye as fadArrowsToEye,
  faPhoneArrowDownLeft as fadPhoneArrowDownLeft,
  faEyeSlash as fadEyeSlash,
  faSignalBars as fadSignalBars, faSignalBarsGood as fadSignalBarsGood,
  faSignalBarsFair as fadSignalBarsFair, faSignalBarsWeak as fadSignalBarsWeak,
  faHandshake as fadHandshake,
  faPersonPregnant as fadPersonPregnant,
  faCreditCard as fadCreditCard,
} from '@adieuu-llc/fa-pro-duotone-svg-icons';

// ---------------------------------------------------------------------------
// DuoTone Thin
// ---------------------------------------------------------------------------

import {
  faHouse as fadtHouse, faMessage as fadtMessage, faReply as fadtReply, faUsers as fadtUsers,
  faGear as fadtGear, faCircleInfo as fadtCircleInfo, faDownload as fadtDownload,
  faRightFromBracket as fadtLogout, faShieldCheck as fadtShield,
  faKey as fadtKey, faBell as fadtBell, faMagnifyingGlass as fadtSearch,
  faUser as fadtUser, faPalette as fadtPalette, faLock as fadtLock,
  faMask as fadtMask, faPlus as fadtPlus, faCheck as fadtCheck,
  faClock as fadtClock, faXmark as fadtX, faGrid2 as fadtSpaces,
  faEllipsis as fadtEllipsis, faEllipsisVertical as fadtEllipsisVertical,
  faLocationPin as fadtLocationPin, faFaceSmile as fadtSmile,
  faFaceSmilePlus as fadtSmilePlus, faPaperPlane as fadtSend,
  faTrash as fadtTrash, faFileExport as fadtFileExport,
  faFileImport as fadtFileImport, faChevronDown as fadtChevronDown,
  faChevronRight as fadtChevronRight, faChevronUp as fadtChevronUp,
  faCamera as fadtCamera, faImage as fadtImage, faGlobe as fadtGlobe,
  faDesktop as fadtDesktop, faBars as fadtBars, faEye as fadtEye,
  faThumbsUp as fadtThumbsUp, faTriangleExclamation as fadtWarning,
  faCircleCheck as fadtSuccess, faCircleXmark as fadtError,
  faBadgeCheck as fadtBadge, faFileArrowDown as fadtFileDown,
  faFileArrowUp as fadtFileUp, faArrowLeft as fadtArrowLeft, faArrowRight as fadtArrowRight,
  faCircle as fadtCircle, faPen as fadtPen,
  faNoteSticky as fadtNoteSticky,
  faTrophy as fadtTrophy, faUserPlus as fadtUserPlus,
  faUserGroup as fadtUserGroup, faMobileScreenButton as fadtMobile,
  faHeart as fadtHeart, faBan as fadtBan, faGavel as fadtGavel,
  faFire as fadtFire, faUserMinus as fadtUserMinus,
  faBoxArchive as fadtBoxArchive, faStar as fadtStar,
  faFilter as fadtFilter, faArrowDownAZ as fadtArrowDownAZ,
  faCopy as fadtCopy, faFiles as fadtFiles, faBorderAll as fadtBorderAll, faLink as fadtLink,
  faArrowUpRightFromSquare as fadtExternalLink,
  faArrowUpFromBracket as fadtArrowUpFromBracket, faFilm as fadtFilm,
  faPhone as fadtPhone, faPhoneHangup as fadtPhoneHangup, faVideo as fadtVideo,
  faVideoSlash as fadtVideoSlash, faMicrophone as fadtMicrophone,
  faMicrophoneSlash as fadtMicrophoneSlash, faScreenUsers as fadtScreenUsers,
  faPhoneArrowDownLeft as fadtPhoneArrowDownLeft,
  faEyeSlash as fadtEyeSlash,
  faSignalBars as fadtSignalBars, faSignalBarsGood as fadtSignalBarsGood,
  faSignalBarsFair as fadtSignalBarsFair, faSignalBarsWeak as fadtSignalBarsWeak,
  faHandshake as fadtHandshake,
  faPersonPregnant as fadtPersonPregnant,
  faCreditCard as fadtCreditCard,
} from '@adieuu-llc/fa-duotone-thin-svg-icons';

// ---------------------------------------------------------------------------
// Sharp DuoTone Solid
// ---------------------------------------------------------------------------

import {
  faHouse as fasdsHouse, faMessage as fasdsMessage, faReply as fasdsReply, faUsers as fasdsUsers,
  faGear as fasdsGear, faCircleInfo as fasdsCircleInfo, faDownload as fasdsDownload,
  faRightFromBracket as fasdsLogout, faShieldCheck as fasdsShield,
  faKey as fasdsKey, faBell as fasdsBell, faMagnifyingGlass as fasdsSearch,
  faUser as fasdsUser, faPalette as fasdsPalette, faLock as fasdsLock,
  faMask as fasdsMask, faPlus as fasdsPlus, faCheck as fasdsCheck,
  faClock as fasdsClock, faXmark as fasdsX, faGrid2 as fasdsSpaces,
  faEllipsis as fasdsEllipsis, faEllipsisVertical as fasdsEllipsisVertical,
  faLocationPin as fasdsLocationPin, faThumbtack as fasdsThumbtack, faFaceSmile as fasdsSmile,
  faFaceSmilePlus as fasdsSmilePlus, faPaperPlane as fasdsSend,
  faTrash as fasdsTrash, faFileExport as fasdsFileExport,
  faFileImport as fasdsFileImport, faChevronDown as fasdsChevronDown,
  faChevronRight as fasdsChevronRight, faChevronUp as fasdsChevronUp,
  faCamera as fasdsCamera, faImage as fasdsImage, faGlobe as fasdsGlobe,
  faDesktop as fasdsDesktop, faBars as fasdsBars, faEye as fasdsEye,
  faThumbsUp as fasdsThumbsUp, faTriangleExclamation as fasdsWarning,
  faCircleCheck as fasdsSuccess, faCircleXmark as fasdsError,
  faBadgeCheck as fasdsBadge, faFileArrowDown as fasdsFileDown,
  faFileArrowUp as fasdsFileUp, faArrowLeft as fasdsArrowLeft, faArrowRight as fasdsArrowRight,
  faCircle as fasdsCircle, faPen as fasdsPen,
  faNoteSticky as fasdsNoteSticky,
  faTrophy as fasdsTrophy, faUserPlus as fasdsUserPlus,
  faUserGroup as fasdsUserGroup, faMobileScreenButton as fasdsMobile,
  faHeart as fasdsHeart, faBan as fasdsBan, faGavel as fasdsGavel,
  faFire as fasdsFire, faUserMinus as fasdsUserMinus,
  faBoxArchive as fasdsBoxArchive, faStar as fasdsStar,
  faFilter as fasdsFilter, faArrowDownAZ as fasdsArrowDownAZ,
  faCopy as fasdsCopy, faFiles as fasdsFiles, faBorderAll as fasdsBorderAll, faLink as fasdsLink,
  faArrowUpRightFromSquare as fasdsExternalLink,
  faArrowUpFromBracket as fasdsArrowUpFromBracket, faFilm as fasdsFilm,
  faPhone as fasdsPhone, faPhoneHangup as fasdsPhoneHangup, faVideo as fasdsVideo,
  faVideoSlash as fasdsVideoSlash, faMicrophone as fasdsMicrophone,
  faMicrophoneSlash as fasdsMicrophoneSlash, faScreenUsers as fasdsScreenUsers,
  faMaximize as fasdsMaximize, faCompress as fasdsCompress,
  faArrowsToEye as fasdsArrowsToEye,
  faPhoneArrowDownLeft as fasdsPhoneArrowDownLeft,
  faEyeSlash as fasdsEyeSlash,
  faSignalBars as fasdsSignalBars, faSignalBarsGood as fasdsSignalBarsGood,
  faSignalBarsFair as fasdsSignalBarsFair, faSignalBarsWeak as fasdsSignalBarsWeak,
  faHandshake as fasdsHandshake,
  faPersonPregnant as fasdsPersonPregnant,
  faCreditCard as fasdsCreditCard,
} from '@adieuu-llc/fa-sharp-duotone-solid-svg-icons';

// ---------------------------------------------------------------------------
// Sharp DuoTone Thin
// ---------------------------------------------------------------------------

import {
  faHouse as fasdtHouse, faMessage as fasdtMessage, faReply as fasdtReply, faUsers as fasdtUsers,
  faGear as fasdtGear, faCircleInfo as fasdtCircleInfo, faDownload as fasdtDownload,
  faRightFromBracket as fasdtLogout, faShieldCheck as fasdtShield,
  faKey as fasdtKey, faBell as fasdtBell, faMagnifyingGlass as fasdtSearch,
  faUser as fasdtUser, faPalette as fasdtPalette, faLock as fasdtLock,
  faMask as fasdtMask, faPlus as fasdtPlus, faCheck as fasdtCheck,
  faClock as fasdtClock, faXmark as fasdtX, faGrid2 as fasdtSpaces,
  faEllipsis as fasdtEllipsis, faEllipsisVertical as fasdtEllipsisVertical,
  faLocationPin as fasdtLocationPin, faThumbtack as fasdtThumbtack, faFaceSmile as fasdtSmile,
  faFaceSmilePlus as fasdtSmilePlus, faPaperPlane as fasdtSend,
  faTrash as fasdtTrash, faFileExport as fasdtFileExport,
  faFileImport as fasdtFileImport, faChevronDown as fasdtChevronDown,
  faChevronRight as fasdtChevronRight, faChevronUp as fasdtChevronUp,
  faCamera as fasdtCamera, faImage as fasdtImage, faGlobe as fasdtGlobe,
  faDesktop as fasdtDesktop, faBars as fasdtBars, faEye as fasdtEye,
  faThumbsUp as fasdtThumbsUp, faTriangleExclamation as fasdtWarning,
  faCircleCheck as fasdtSuccess, faCircleXmark as fasdtError,
  faBadgeCheck as fasdtBadge, faFileArrowDown as fasdtFileDown,
  faFileArrowUp as fasdtFileUp, faArrowLeft as fasdtArrowLeft, faArrowRight as fasdtArrowRight,
  faCircle as fasdtCircle, faPen as fasdtPen,
  faNoteSticky as fasdtNoteSticky,
  faTrophy as fasdtTrophy, faUserPlus as fasdtUserPlus,
  faUserGroup as fasdtUserGroup, faMobileScreenButton as fasdtMobile,
  faHeart as fasdtHeart, faBan as fasdtBan, faGavel as fasdtGavel,
  faFire as fasdtFire, faUserMinus as fasdtUserMinus,
  faBoxArchive as fasdtBoxArchive, faStar as fasdtStar,
  faFilter as fasdtFilter, faArrowDownAZ as fasdtArrowDownAZ,
  faCopy as fasdtCopy, faFiles as fasdtFiles, faBorderAll as fasdtBorderAll, faLink as fasdtLink,
  faArrowUpRightFromSquare as fasdtExternalLink,
  faArrowUpFromBracket as fasdtArrowUpFromBracket, faFilm as fasdtFilm,
  faPhone as fasdtPhone, faPhoneHangup as fasdtPhoneHangup, faVideo as fasdtVideo,
  faVideoSlash as fasdtVideoSlash, faMicrophone as fasdtMicrophone,
  faMicrophoneSlash as fasdtMicrophoneSlash, faScreenUsers as fasdtScreenUsers,
  faMaximize as fasdtMaximize, faCompress as fasdtCompress,
  faArrowsToEye as fasdtArrowsToEye,
  faPhoneArrowDownLeft as fasdtPhoneArrowDownLeft,
  faEyeSlash as fasdtEyeSlash,
  faSignalBars as fasdtSignalBars, faSignalBarsGood as fasdtSignalBarsGood,
  faSignalBarsFair as fasdtSignalBarsFair, faSignalBarsWeak as fasdtSignalBarsWeak,
  faHandshake as fasdtHandshake,
  faPersonPregnant as fasdtPersonPregnant,
  faCreditCard as fasdtCreditCard,
} from '@adieuu-llc/fa-sharp-duotone-thin-svg-icons';

// ---------------------------------------------------------------------------
// Register everything with the FA library
// ---------------------------------------------------------------------------

const allIcons: IconDefinition[] = [
  // Classic Solid
  fasHouse, fasMessage, fasReply, fasUsers, fasGear, fasCircleInfo, fasDownload,
  fasLogout, fasShield, fasKey, fasBell, fasSearch, fasUser, fasPalette,
  fasLock, fasMask, fasPlus, fasCheck, fasClock, fasX, fasSpaces,
  fasEllipsis, fasEllipsisVertical, fasLocationPin, fasThumbtack, fasSmile, fasSmilePlus, fasSend, fasTrash, fasFileExport,
  fasFileImport, fasChevronDown, fasChevronRight, fasChevronUp, fasCamera,
  fasImage, fasGlobe, fasDesktop, fasBars, fasEye, fasThumbsUp,
  fasWarning, fasSuccess, fasError, fasBadge, fasFileDown, fasFileUp,
  fasArrowLeft, fasArrowRight, fasCircle, fasPen, fasNoteSticky,
  fasTrophy, fasUserPlus, fasUserGroup, fasMobile, fasHeart, fasBan, fasGavel,
  fasFire, fasUserMinus,
  fasBoxArchive, fasStar, fasFilter, fasArrowDownAZ,
  fasCopy, fasFiles, fasBorderAll, fasLink, fasExternalLink, fasArrowUpFromBracket, fasFilm,
  fasPhone, fasPhoneHangup, fasVideo, fasVideoSlash, fasMicrophone,
  fasMicrophoneSlash, fasScreenUsers, fasPhoneArrowDownLeft, fasEyeSlash,
  fasMaximize, fasCompress, fasArrowsToEye,
  fasSignalBars, fasSignalBarsGood, fasSignalBarsFair, fasSignalBarsWeak,
  fasHandshake,
  fasPersonPregnant,
  fasCreditCard,

  // DuoTone Solid
  fadHouse, fadMessage, fadReply, fadUsers, fadGear, fadCircleInfo, fadDownload,
  fadLogout, fadShield, fadKey, fadBell, fadSearch, fadUser, fadPalette,
  fadLock, fadMask, fadPlus, fadCheck, fadClock, fadX, fadSpaces,
  fadEllipsis, fadEllipsisVertical, fadLocationPin, fadThumbtack, fadSmile, fadSmilePlus, fadSend, fadTrash, fadFileExport,
  fadFileImport, fadChevronDown, fadChevronRight, fadChevronUp, fadCamera,
  fadImage, fadGlobe, fadDesktop, fadBars, fadEye, fadThumbsUp,
  fadWarning, fadSuccess, fadError, fadBadge, fadFileDown, fadFileUp,
  fadArrowLeft, fadArrowRight, fadCircle, fadPen, fadNoteSticky,
  fadTrophy, fadUserPlus, fadUserGroup, fadMobile, fadHeart, fadBan, fadGavel,
  fadFire, fadUserMinus,
  fadBoxArchive, fadStar, fadFilter, fadArrowDownAZ,
  fadCopy, fadFiles, fadBorderAll, fadLink, fadExternalLink, fadArrowUpFromBracket, fadFilm,
  fadPhone, fadPhoneHangup, fadVideo, fadVideoSlash, fadMicrophone,
  fadMicrophoneSlash, fadScreenUsers, fadPhoneArrowDownLeft, fadEyeSlash,
  fadMaximize, fadCompress, fadArrowsToEye,
  fadSignalBars, fadSignalBarsGood, fadSignalBarsFair, fadSignalBarsWeak,
  fadHandshake,
  fadPersonPregnant,
  fadCreditCard,

  // DuoTone Thin
  fadtHouse, fadtMessage, fadtReply, fadtUsers, fadtGear, fadtCircleInfo, fadtDownload,
  fadtLogout, fadtShield, fadtKey, fadtBell, fadtSearch, fadtUser, fadtPalette,
  fadtLock, fadtMask, fadtPlus, fadtCheck, fadtClock, fadtX, fadtSpaces,
  fadtEllipsis, fadtEllipsisVertical, fadtLocationPin, fadtSmile, fadtSmilePlus, fadtSend, fadtTrash, fadtFileExport,
  fadtFileImport, fadtChevronDown, fadtChevronRight, fadtChevronUp, fadtCamera,
  fadtImage, fadtGlobe, fadtDesktop, fadtBars, fadtEye, fadtThumbsUp,
  fadtWarning, fadtSuccess, fadtError, fadtBadge, fadtFileDown, fadtFileUp,
  fadtArrowLeft, fadtArrowRight, fadtCircle, fadtPen, fadtNoteSticky,
  fadtTrophy, fadtUserPlus, fadtUserGroup, fadtMobile, fadtHeart, fadtBan, fadtGavel,
  fadtFire, fadtUserMinus,
  fadtBoxArchive, fadtStar, fadtFilter, fadtArrowDownAZ,
  fadtCopy, fadtFiles, fadtBorderAll, fadtLink, fadtExternalLink, fadtArrowUpFromBracket, fadtFilm,
  fadtPhone, fadtPhoneHangup, fadtVideo, fadtVideoSlash, fadtMicrophone,
  fadtMicrophoneSlash, fadtScreenUsers, fadtPhoneArrowDownLeft, fadtEyeSlash,
  fadtSignalBars, fadtSignalBarsGood, fadtSignalBarsFair, fadtSignalBarsWeak,
  fadtHandshake,
  fadtPersonPregnant,
  fadtCreditCard,

  // Sharp DuoTone Solid
  fasdsHouse, fasdsMessage, fasdsReply, fasdsUsers, fasdsGear, fasdsCircleInfo, fasdsDownload,
  fasdsLogout, fasdsShield, fasdsKey, fasdsBell, fasdsSearch, fasdsUser, fasdsPalette,
  fasdsLock, fasdsMask, fasdsPlus, fasdsCheck, fasdsClock, fasdsX, fasdsSpaces,
  fasdsEllipsis, fasdsEllipsisVertical, fasdsLocationPin, fasdsThumbtack, fasdsSmile, fasdsSmilePlus, fasdsSend, fasdsTrash, fasdsFileExport,
  fasdsFileImport, fasdsChevronDown, fasdsChevronRight, fasdsChevronUp, fasdsCamera,
  fasdsImage, fasdsGlobe, fasdsDesktop, fasdsBars, fasdsEye, fasdsThumbsUp,
  fasdsWarning, fasdsSuccess, fasdsError, fasdsBadge, fasdsFileDown, fasdsFileUp,
  fasdsArrowLeft, fasdsArrowRight, fasdsCircle, fasdsPen, fasdsNoteSticky,
  fasdsTrophy, fasdsUserPlus, fasdsUserGroup, fasdsMobile, fasdsHeart, fasdsBan, fasdsGavel,
  fasdsFire, fasdsUserMinus,
  fasdsBoxArchive, fasdsStar, fasdsFilter, fasdsArrowDownAZ,
  fasdsCopy, fasdsFiles, fasdsBorderAll, fasdsLink, fasdsExternalLink, fasdsArrowUpFromBracket, fasdsFilm,
  fasdsPhone, fasdsPhoneHangup, fasdsVideo, fasdsVideoSlash, fasdsMicrophone,
  fasdsMicrophoneSlash, fasdsScreenUsers, fasdsPhoneArrowDownLeft, fasdsEyeSlash,
  fasdsMaximize, fasdsCompress, fasdsArrowsToEye,
  fasdsSignalBars, fasdsSignalBarsGood, fasdsSignalBarsFair, fasdsSignalBarsWeak,
  fasdsHandshake,
  fasdsPersonPregnant,
  fasdsCreditCard,

  // Sharp DuoTone Thin
  fasdtHouse, fasdtMessage, fasdtReply, fasdtUsers, fasdtGear, fasdtCircleInfo, fasdtDownload,
  fasdtLogout, fasdtShield, fasdtKey, fasdtBell, fasdtSearch, fasdtUser, fasdtPalette,
  fasdtLock, fasdtMask, fasdtPlus, fasdtCheck, fasdtClock, fasdtX, fasdtSpaces,
  fasdtEllipsis, fasdtEllipsisVertical, fasdtLocationPin, fasdtThumbtack, fasdtSmile, fasdtSmilePlus, fasdtSend, fasdtTrash, fasdtFileExport,
  fasdtFileImport, fasdtChevronDown, fasdtChevronRight, fasdtChevronUp, fasdtCamera,
  fasdtImage, fasdtGlobe, fasdtDesktop, fasdtBars, fasdtEye, fasdtThumbsUp,
  fasdtWarning, fasdtSuccess, fasdtError, fasdtBadge, fasdtFileDown, fasdtFileUp,
  fasdtArrowLeft, fasdtArrowRight, fasdtCircle, fasdtPen, fasdtNoteSticky,
  fasdtTrophy, fasdtUserPlus, fasdtUserGroup, fasdtMobile, fasdtHeart, fasdtBan, fasdtGavel,
  fasdtFire, fasdtUserMinus,
  fasdtBoxArchive, fasdtStar, fasdtFilter, fasdtArrowDownAZ,
  fasdtCopy, fasdtFiles, fasdtBorderAll, fasdtLink, fasdtExternalLink, fasdtArrowUpFromBracket, fasdtFilm,
  fasdtPhone, fasdtPhoneHangup, fasdtVideo, fasdtVideoSlash, fasdtMicrophone,
  fasdtMicrophoneSlash, fasdtScreenUsers, fasdtPhoneArrowDownLeft, fasdtEyeSlash,
  fasdtMaximize, fasdtCompress, fasdtArrowsToEye,
  fasdtSignalBars, fasdtSignalBarsGood, fasdtSignalBarsFair, fasdtSignalBarsWeak,
  fasdtHandshake,
  fasdtPersonPregnant,
  fasdtCreditCard,
];

library.add(...allIcons);
