/**
 * Request ID Middleware
 * 
 * Adds the request ID to response headers for distributed tracing and debugging.
 * The request ID is either extracted from the incoming `X-Request-ID` header
 * (if provided by a proxy) or generated by the router.
 * 
 * Use cases:
 * - Correlating logs across services
 * - Tracing requests through distributed systems
 * - Debugging production issues
 * - Support ticket correlation
 * 
 * @module middleware/request-id
 * 
 * @example
 * ```typescript
 * import { requestId } from './middleware';
 * 
 * const app = new Router();
 * app.use(requestId());
 * 
 * // Responses will include:
 * // X-Request-ID: 550e8400-e29b-41d4-a716-446655440000
 * ```
 */

import type { Middleware } from '../router';

/**
 * Creates a request ID middleware.
 * 
 * Returns a middleware function that adds the `X-Request-ID` header to all
 * responses. The ID is taken from `ctx.requestId`, which is set by the router
 * either from an incoming header or generated as a new UUID.
 * 
 * @returns Middleware function that adds request ID header
 * 
 * @example
 * ```typescript
 * import { Router } from './router';
 * import { requestId } from './middleware';
 * 
 * const app = new Router();
 * 
 * // Add request ID to all responses
 * app.use(requestId());
 * 
 * app.get('/api/users', async (ctx) => {
 *   // Access the request ID in handlers
 *   console.log('Request ID:', ctx.requestId);
 *   
 *   // Include in logs for correlation
 *   logger.info('Fetching users', { requestId: ctx.requestId });
 *   
 *   return success(users);
 * });
 * 
 * // Response headers:
 * // X-Request-ID: 550e8400-e29b-41d4-a716-446655440000
 * ```
 * 
 * @example
 * ```typescript
 * // Client-side usage for support
 * try {
 *   const response = await fetch('/api/users');
 *   const requestId = response.headers.get('X-Request-ID');
 *   
 *   if (!response.ok) {
 *     // Include request ID in error reports
 *     reportError({
 *       message: 'API request failed',
 *       requestId,
 *       status: response.status,
 *     });
 *   }
 * } catch (error) {
 *   // Request ID helps support find the exact request in logs
 * }
 * ```
 */
export function requestId(): Middleware {
  return async (ctx, next) => {
    const response = await next();
    const headers = new Headers(response.headers);
    headers.set('X-Request-ID', ctx.requestId);

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  };
}
